## Урок 17. Pandas, часть 3

In [1]:
import pandas as pd # импорт библиотеки Pandas

### 1. Объединение датафреймов методами merge и concat

In [264]:
df1 = pd.read_csv('/Users/sherlock/Downloads/IHME-GBD_2019_DATA-15798851-2/IHME-GBD_2019_DATA-15798851-2.csv')

# загружем 1-ый файл, сохранненный на компьютере
# ссылка на скачивание https://drive.google.com/file/d/1uK1edpdqVFJnFaGTWGpVOlaJHgoCBwli/view?usp=sharing 
# источник данных Global Burden of Disease Study 2019 (GBD 2019) Results.
# Seattle, United States: Institute for Health Metrics and Evaluation (IHME), 2020.
# Сайт http://ghdx.healthdata.org/gbd-results-tool
# DALYs (Disability-Adjusted Life Years) — этот показатель означает, 
# сколько лет здоровой и продуктивной жизни люди теряют из-за нетрудоспособности и ранней смерти от разных болезней

df1.head(10) # выводим первые 10 строк

,measure,location,sex,age,cause,metric,year,val,upper,lower
0,DALYs (Disability-Adjusted Life Years),Gambia,Female,All Ages,Maternal and neonatal disorders,Rate,2012,7475.212700,9104.773541,6157.428603
1,DALYs (Disability-Adjusted Life Years),Gambia,Both,All Ages,Maternal and neonatal disorders,Rate,2012,7814.344518,9667.960848,6289.146375
2,DALYs (Disability-Adjusted Life Years),Gambia,Male,All Ages,Substance use disorders,Number,2012,1659.038707,2126.829521,1239.172699
3,DALYs (Disability-Adjusted Life Years),Gambia,Female,All Ages,Substance use disorders,Number,2012,874.432466,1186.560596,618.271780
4,DALYs (Disability-Adjusted Life Years),Gambia,Both,All Ages,Substance use disorders,Number,2012,2533.471173,3231.220866,1868.204609
5,DALYs (Disability-Adjusted Life Years),Gambia,Male,All Ages,Substance use disorders,Percent,2012,0.003799,0.004849,0.002863
6,DALYs (Disability-Adjusted Life Years),Gambia,Female,All Ages,Substance use disorders,Percent,2012,0.002202,0.002889,0.001585
7,DALYs (Disability-Adjusted Life Years),Gambia,Both,All Ages,Substance use disorders,Percent,2012,0.003038,0.003885,0.002298
8,DALYs (Disability-Adjusted Life Years),Gambia,Male,All Ages,Substance use disorders,Rate,2012,179.493660,230.104586,134.067784
9,DALYs (Disability-Adjusted Life Years),Gambia,Female,All Ages,Substance use disorders,Rate,2012,91.400543,124.025911,64.625204

In [265]:
df2 = pd.read_csv("/Users/sherlock/Downloads/IHME-GBD_2019_DATA-ff08d9bc-1/IHME-GBD_2019_DATA-ff08d9bc-1.csv")

# загружем 1-ый файл, сохранненный на компьютере
# ссылка на скачивание https://drive.google.com/file/d/16fM_JEC5GAkYEDaDgzROrBm8loi9RZRZ/view
# источник данных Global Burden of Disease Study 2019 (GBD 2019) Results, сайт http://ghdx.healthdata.org/gbd-results-tool
# в файле данные о смертности людей от разных причин по 204 странам с 2000 по 2019 гг

df2.head(10)

,measure,location,sex,age,cause,metric,year,val,upper,lower
0,Deaths,Samoa,Male,All Ages,Chronic respiratory diseases,Rate,2000,64.470214,81.808307,53.476793
1,Deaths,Samoa,Female,All Ages,Chronic respiratory diseases,Rate,2000,55.234399,77.883497,39.978647
2,Deaths,Samoa,Both,All Ages,Chronic respiratory diseases,Rate,2000,60.039961,76.013089,49.941986
3,Deaths,Samoa,Male,All Ages,Skin and subcutaneous diseases,Rate,2000,2.246741,3.467454,1.438979
4,Deaths,Samoa,Female,All Ages,Skin and subcutaneous diseases,Rate,2000,1.368385,1.945448,0.866099
5,Deaths,Samoa,Both,All Ages,Skin and subcutaneous diseases,Rate,2000,1.825409,2.569260,1.259226
6,Deaths,Samoa,Male,All Ages,Transport injuries,Rate,2000,25.920294,36.084587,18.130636
7,Deaths,Samoa,Female,All Ages,Transport injuries,Rate,2000,10.099048,13.447738,7.330908
8,Deaths,Samoa,Both,All Ages,Transport injuries,Rate,2000,18.331128,25.000813,13.148053
9,Deaths,Samoa,Male,All Ages,Unintentional injuries,Rate,2000,28.989384,39.579940,20.833239

In [266]:
df1.rename(columns = {'val': 'daly_val', 'upper':'daly_upper', 'lower':'daly_lower'}, inplace = True)
df2.rename(columns = {'val': 'deaths_val', 'upper': 'deaths_upper', 'lower':'deaths_lower'}, inplace = True)
# меняем названия колонок в соответствии с показателями: число потерянных продуктивых лет для 1-го датафрейма (DALY)
# и смертность для 2-го датафрейма ()

In [267]:
df_all = pd.merge(df1, df2, on = ['location', 'sex', 'age', 'cause', 'metric', 'year'], how = 'inner') 

# inner: берем только совпадения из двух датафреймов 
# у нас указаны названия колонок, по которым мы объединяем датафреймы, но также можно объединять по индексу — 
# порядковому номеру, который слева по вертикали c помощью [df1.index] без кавывек

In [268]:
# pd.merge(df1, df2, on = ['column name'], how='inner') # берем только строки, совпадающие в обоих датафреймах
# pd.merge(df1, df2, on = ['column name'], how='outer') # все строки из всех датафреймов, не важно совпадающие или нет 
# pd.merge(df1, df2, on = ['column name'], how='left') # только совпадающие строки + все строки из левого датафрейма 
# pd.merge(df1, df2, on = ['column name'], how='right') только совпадающие строки + все строки из правого датафрейма

In [269]:
df_all.head()

,measure_x,location,sex,age,cause,metric,year,daly_val,daly_upper,daly_lower,measure_y,deaths_val,deaths_upper,deaths_lower
0,DALYs (Disability-Adjusted Life Years),Gambia,Female,All Ages,Maternal and neonatal disorders,Rate,2012,7475.212700,9104.773541,6157.428603,Deaths,89.867238,110.176286,74.001324
1,DALYs (Disability-Adjusted Life Years),Gambia,Both,All Ages,Maternal and neonatal disorders,Rate,2012,7814.344518,9667.960848,6289.146375,Deaths,89.365457,111.497307,71.539316
2,DALYs (Disability-Adjusted Life Years),Gambia,Male,All Ages,Substance use disorders,Rate,2012,179.493660,230.104586,134.067784,Deaths,1.101136,1.545407,0.786638
3,DALYs (Disability-Adjusted Life Years),Gambia,Female,All Ages,Substance use disorders,Rate,2012,91.400543,124.025911,64.625204,Deaths,0.227136,0.296917,0.173921
4,DALYs (Disability-Adjusted Life Years),Gambia,Both,All Ages,Substance use disorders,Rate,2012,134.688036,171.782808,99.320179,Deaths,0.656605,0.896138,0.490594

In [295]:
df_all.shape # сколько строк и колонок в датафрейме

(97976, 15)

In [296]:
 # делим датафрейм на два датафрейма: 1-ый со строками от первой до 50 000, 2-ой от 50000 до последней
df_all_1 = df_all.iloc[:50000,:]
df_all_2 = df_all.iloc[50000:,:]

In [297]:
df_all_new = pd.concat([df_all_1, df_all_2], axis = 0) # объединяем датафреймы: если axis = 0, то по строкам, если 
# axis = 1, то по столбцам
df_all_new.shape # в новом датафрейме снова столько же строк и столбцов, сколько было до разделения

(97976, 15)

### 2.1. Добавление новых столбцов с помощью математических операций

In [303]:
# добавляем новый столбец, в котором будет округленное значение из другого столбца
df_all["deaths_val_round"] = df_all["deaths_val"].round(decimals = 1)

In [307]:
df_all

,measure_x,location,sex,age,cause,metric,year,daly_val,daly_upper,daly_lower,measure_y,deaths_val,deaths_upper,deaths_lower,deaths_val_round
0,DALYs (Disability-Adjusted Life Years),Gambia,Female,All Ages,Maternal and neonatal disorders,Rate,2012,7475.212700,9104.773541,6157.428603,Deaths,89.867238,110.176286,74.001324,89.9
1,DALYs (Disability-Adjusted Life Years),Gambia,Both,All Ages,Maternal and neonatal disorders,Rate,2012,7814.344518,9667.960848,6289.146375,Deaths,89.365457,111.497307,71.539316,89.4
2,DALYs (Disability-Adjusted Life Years),Gambia,Male,All Ages,Substance use disorders,Rate,2012,179.493660,230.104586,134.067784,Deaths,1.101136,1.545407,0.786638,1.1
3,DALYs (Disability-Adjusted Life Years),Gambia,Female,All Ages,Substance use disorders,Rate,2012,91.400543,124.025911,64.625204,Deaths,0.227136,0.296917,0.173921,0.2
4,DALYs (Disability-Adjusted Life Years),Gambia,Both,All Ages,Substance use disorders,Rate,2012,134.688036,171.782808,99.320179,Deaths,0.656605,0.896138,0.490594,0.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97971,DALYs (Disability-Adjusted Life Years),Malawi,Female,All Ages,Chronic respiratory diseases,Rate,2019,602.342558,732.856075,491.019574,Deaths,10.783192,13.484120,8.267941,10.8
97972,DALYs (Disability-Adjusted Life Years),Malawi,Both,All Ages,Chronic respiratory diseases,Rate,2019,635.274862,755.292643,530.146531,Deaths,13.025678,15.412885,10.664151,13.0
97973,DALYs (Disability-Adjusted Life Years),Malawi,Male,All Ages,Unintentional injuries,Rate,2019,1318.844977,1717.917036,1037.489279,Deaths,20.824550,27.026330,16.310791,20.8
97974,DALYs (Disability-Adjusted Life Years),Malawi,Female,All Ages,Unintentional injuries,Rate,2019,813.052440,1042.011143,638.605025,Deaths,11.865525,15.430914,9.199714,11.9
97975,DALYs (Disability-Adjusted Life Years),Malawi,Both,All Ages,Unintentional injuries,Rate,2019,1059.021476,1334.453539,846.543870,Deaths,16.222336,20.617369,12.836190,16.2

In [308]:
# добавляем новый столбец, суммируя значения нескольких других
df_all["deaths_total"] = df_all["deaths_val"] + df_all["deaths_upper"] + df_all["deaths_lower"]
df_all

,measure_x,location,sex,age,cause,metric,year,daly_val,daly_upper,daly_lower,measure_y,deaths_val,deaths_upper,deaths_lower,deaths_val_round,deaths_total
0,DALYs (Disability-Adjusted Life Years),Gambia,Female,All Ages,Maternal and neonatal disorders,Rate,2012,7475.212700,9104.773541,6157.428603,Deaths,89.867238,110.176286,74.001324,89.9,274.044849
1,DALYs (Disability-Adjusted Life Years),Gambia,Both,All Ages,Maternal and neonatal disorders,Rate,2012,7814.344518,9667.960848,6289.146375,Deaths,89.365457,111.497307,71.539316,89.4,272.402080
2,DALYs (Disability-Adjusted Life Years),Gambia,Male,All Ages,Substance use disorders,Rate,2012,179.493660,230.104586,134.067784,Deaths,1.101136,1.545407,0.786638,1.1,3.433182
3,DALYs (Disability-Adjusted Life Years),Gambia,Female,All Ages,Substance use disorders,Rate,2012,91.400543,124.025911,64.625204,Deaths,0.227136,0.296917,0.173921,0.2,0.697975
4,DALYs (Disability-Adjusted Life Years),Gambia,Both,All Ages,Substance use disorders,Rate,2012,134.688036,171.782808,99.320179,Deaths,0.656605,0.896138,0.490594,0.7,2.043338
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97971,DALYs (Disability-Adjusted Life Years),Malawi,Female,All Ages,Chronic respiratory diseases,Rate,2019,602.342558,732.856075,491.019574,Deaths,10.783192,13.484120,8.267941,10.8,32.535253
97972,DALYs (Disability-Adjusted Life Years),Malawi,Both,All Ages,Chronic respiratory diseases,Rate,2019,635.274862,755.292643,530.146531,Deaths,13.025678,15.412885,10.664151,13.0,39.102714
97973,DALYs (Disability-Adjusted Life Years),Malawi,Male,All Ages,Unintentional injuries,Rate,2019,1318.844977,1717.917036,1037.489279,Deaths,20.824550,27.026330,16.310791,20.8,64.161670
97974,DALYs (Disability-Adjusted Life Years),Malawi,Female,All Ages,Unintentional injuries,Rate,2019,813.052440,1042.011143,638.605025,Deaths,11.865525,15.430914,9.199714,11.9,36.496153
97975,DALYs (Disability-Adjusted Life Years),Malawi,Both,All Ages,Unintentional injuries,Rate,2019,1059.021476,1334.453539,846.543870,Deaths,16.222336,20.617369,12.836190,16.2,49.675896

In [309]:
# добавляем новый столбец, суммируя значения нескольких других с помощью метода loc
# помимо sum, можно считать mean (среднее), median (медиана), max, min, std (стандарт.отклонение) и пр.
df_all["total_loc"] = df_all.loc[:, "deaths_val":"deaths_lower"].sum(axis = 1)
df_all

,measure_x,location,sex,age,cause,metric,year,daly_val,daly_upper,daly_lower,measure_y,deaths_val,deaths_upper,deaths_lower,deaths_val_round,deaths_total,total_loc
0,DALYs (Disability-Adjusted Life Years),Gambia,Female,All Ages,Maternal and neonatal disorders,Rate,2012,7475.212700,9104.773541,6157.428603,Deaths,89.867238,110.176286,74.001324,89.9,274.044849,274.044849
1,DALYs (Disability-Adjusted Life Years),Gambia,Both,All Ages,Maternal and neonatal disorders,Rate,2012,7814.344518,9667.960848,6289.146375,Deaths,89.365457,111.497307,71.539316,89.4,272.402080,272.402080
2,DALYs (Disability-Adjusted Life Years),Gambia,Male,All Ages,Substance use disorders,Rate,2012,179.493660,230.104586,134.067784,Deaths,1.101136,1.545407,0.786638,1.1,3.433182,3.433182
3,DALYs (Disability-Adjusted Life Years),Gambia,Female,All Ages,Substance use disorders,Rate,2012,91.400543,124.025911,64.625204,Deaths,0.227136,0.296917,0.173921,0.2,0.697975,0.697975
4,DALYs (Disability-Adjusted Life Years),Gambia,Both,All Ages,Substance use disorders,Rate,2012,134.688036,171.782808,99.320179,Deaths,0.656605,0.896138,0.490594,0.7,2.043338,2.043338
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97971,DALYs (Disability-Adjusted Life Years),Malawi,Female,All Ages,Chronic respiratory diseases,Rate,2019,602.342558,732.856075,491.019574,Deaths,10.783192,13.484120,8.267941,10.8,32.535253,32.535253
97972,DALYs (Disability-Adjusted Life Years),Malawi,Both,All Ages,Chronic respiratory diseases,Rate,2019,635.274862,755.292643,530.146531,Deaths,13.025678,15.412885,10.664151,13.0,39.102714,39.102714
97973,DALYs (Disability-Adjusted Life Years),Malawi,Male,All Ages,Unintentional injuries,Rate,2019,1318.844977,1717.917036,1037.489279,Deaths,20.824550,27.026330,16.310791,20.8,64.161670,64.161670
97974,DALYs (Disability-Adjusted Life Years),Malawi,Female,All Ages,Unintentional injuries,Rate,2019,813.052440,1042.011143,638.605025,Deaths,11.865525,15.430914,9.199714,11.9,36.496153,36.496153
97975,DALYs (Disability-Adjusted Life Years),Malawi,Both,All Ages,Unintentional injuries,Rate,2019,1059.021476,1334.453539,846.543870,Deaths,16.222336,20.617369,12.836190,16.2,49.675896,49.675896

In [321]:
# добавляем новый столбец, суммируя значения нескольких других с помощью метода iloc
# важно, что при использовании метода iloc правое значение (номер столбца) не включается, поэтому если нам нужны столбцы с номерами
# 11, 12 и 13, указать нужно по с 11 по 14-й: df_all.iloc[:, 11:14] 

df_all["total_iloc"] = df_all.iloc[:, 11:14].sum(axis = 1)

In [322]:
df_all

,measure_x,location,sex,age,cause,metric,year,daly_val,daly_upper,daly_lower,measure_y,deaths_val,deaths_upper,deaths_lower,deaths_val_round,deaths_total,total_loc,total_iloc
0,DALYs (Disability-Adjusted Life Years),Gambia,Female,All Ages,Maternal and neonatal disorders,Rate,2012,7475.212700,9104.773541,6157.428603,Deaths,89.867238,110.176286,74.001324,89.9,274.044849,274.044849,274.044849
1,DALYs (Disability-Adjusted Life Years),Gambia,Both,All Ages,Maternal and neonatal disorders,Rate,2012,7814.344518,9667.960848,6289.146375,Deaths,89.365457,111.497307,71.539316,89.4,272.402080,272.402080,272.402080
2,DALYs (Disability-Adjusted Life Years),Gambia,Male,All Ages,Substance use disorders,Rate,2012,179.493660,230.104586,134.067784,Deaths,1.101136,1.545407,0.786638,1.1,3.433182,3.433182,3.433182
3,DALYs (Disability-Adjusted Life Years),Gambia,Female,All Ages,Substance use disorders,Rate,2012,91.400543,124.025911,64.625204,Deaths,0.227136,0.296917,0.173921,0.2,0.697975,0.697975,0.697975
4,DALYs (Disability-Adjusted Life Years),Gambia,Both,All Ages,Substance use disorders,Rate,2012,134.688036,171.782808,99.320179,Deaths,0.656605,0.896138,0.490594,0.7,2.043338,2.043338,2.043338
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97971,DALYs (Disability-Adjusted Life Years),Malawi,Female,All Ages,Chronic respiratory diseases,Rate,2019,602.342558,732.856075,491.019574,Deaths,10.783192,13.484120,8.267941,10.8,32.535253,32.535253,32.535253
97972,DALYs (Disability-Adjusted Life Years),Malawi,Both,All Ages,Chronic respiratory diseases,Rate,2019,635.274862,755.292643,530.146531,Deaths,13.025678,15.412885,10.664151,13.0,39.102714,39.102714,39.102714
97973,DALYs (Disability-Adjusted Life Years),Malawi,Male,All Ages,Unintentional injuries,Rate,2019,1318.844977,1717.917036,1037.489279,Deaths,20.824550,27.026330,16.310791,20.8,64.161670,64.161670,64.161670
97974,DALYs (Disability-Adjusted Life Years),Malawi,Female,All Ages,Unintentional injuries,Rate,2019,813.052440,1042.011143,638.605025,Deaths,11.865525,15.430914,9.199714,11.9,36.496153,36.496153,36.496153
97975,DALYs (Disability-Adjusted Life Years),Malawi,Both,All Ages,Unintentional injuries,Rate,2019,1059.021476,1334.453539,846.543870,Deaths,16.222336,20.617369,12.836190,16.2,49.675896,49.675896,49.675896

In [ ]:
# удалим ненужные столбцы, чтобы не мешали
df_all.drop(['deaths_val_round','deaths_total', 'total_loc','total_iloc'], axis = 1, inplace = True)

### 2.2. Добавление новых столбцов с помощью lambda функций

In [327]:
# создаем список стран, входивших в 2020 году в СНГ
CIS_2020 = ['Azerbaijan', 'Armenia', 'Belarus', 'Kazakhstan', 'Kyrgyzstan', 
            'Moldova', 'Russian Federation', 'Tajikistan', 'Uzbekistan']

In [328]:
# с помощью lambda-функции прописываем, что если страна ('location') входит в СНГ, то пусть в новом столбце 'CIS_2020' 
# будет True, а если нет, то False
df_all['CIS_2020'] = df_all['location'].apply(lambda x: True if x in CIS_2020 else False )
df_all[df_all['CIS_2020'] == True]

,measure_x,location,sex,age,cause,metric,year,daly_val,daly_upper,daly_lower,measure_y,deaths_val,deaths_upper,deaths_lower,CIS_2020
26,DALYs (Disability-Adjusted Life Years),Russian Federation,Male,All Ages,Transport injuries,Rate,2013,2311.203652,2557.790575,2102.970106,Deaths,33.102775,33.670112,31.914774,True
27,DALYs (Disability-Adjusted Life Years),Russian Federation,Female,All Ages,Transport injuries,Rate,2013,1003.703949,1204.231323,826.997768,Deaths,10.021556,10.217613,9.439502,True
28,DALYs (Disability-Adjusted Life Years),Russian Federation,Both,All Ages,Transport injuries,Rate,2013,1610.409759,1827.886031,1418.823756,Deaths,20.731699,21.055609,19.955321,True
95,DALYs (Disability-Adjusted Life Years),Russian Federation,Male,All Ages,Cardiovascular diseases,Rate,2013,16913.285219,17121.473215,16646.640694,Deaths,689.563171,698.231847,671.841370,True
96,DALYs (Disability-Adjusted Life Years),Russian Federation,Female,All Ages,Cardiovascular diseases,Rate,2013,12062.770301,12439.589972,11455.512603,Deaths,730.915208,756.090049,678.546166,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95820,DALYs (Disability-Adjusted Life Years),Uzbekistan,Female,All Ages,Unintentional injuries,Rate,2019,924.906883,1110.802656,764.324202,Deaths,8.090781,9.449337,6.931106,True
95821,DALYs (Disability-Adjusted Life Years),Uzbekistan,Both,All Ages,Unintentional injuries,Rate,2019,1489.541043,1751.864358,1263.197669,Deaths,16.076524,18.680623,13.813033,True
95873,DALYs (Disability-Adjusted Life Years),Armenia,Male,All Ages,Digestive diseases,Rate,2019,1890.952170,2175.781400,1600.627590,Deaths,65.149955,76.413600,54.884648,True
95874,DALYs (Disability-Adjusted Life Years),Armenia,Female,All Ages,Digestive diseases,Rate,2019,1134.309391,1299.771431,975.433185,Deaths,49.340143,57.384637,41.791501,True
95875,DALYs (Disability-Adjusted Life Years),Armenia,Both,All Ages,Digestive diseases,Rate,2019,1499.511198,1724.193941,1286.684471,Deaths,56.970919,66.339240,48.503861,True

In [285]:
# можно записать и короче, не прописывая полностью это условие
df_all['CIS_2020'] = df_all['location'].apply(lambda x: x in CIS_2020)

In [286]:
# выберем строки, которые соответствуют новому условию и проверим, удалось ли их добавить 
df_all[df_all['CIS_2020'] == True]

,measure_x,location,sex,age,cause,metric,year,daly_val,daly_upper,daly_lower,measure_y,deaths_val,deaths_upper,deaths_lower,CIS_2020
26,DALYs (Disability-Adjusted Life Years),Russian Federation,Male,All Ages,Transport injuries,Rate,2013,2311.203652,2557.790575,2102.970106,Deaths,33.102775,33.670112,31.914774,True
27,DALYs (Disability-Adjusted Life Years),Russian Federation,Female,All Ages,Transport injuries,Rate,2013,1003.703949,1204.231323,826.997768,Deaths,10.021556,10.217613,9.439502,True
28,DALYs (Disability-Adjusted Life Years),Russian Federation,Both,All Ages,Transport injuries,Rate,2013,1610.409759,1827.886031,1418.823756,Deaths,20.731699,21.055609,19.955321,True
95,DALYs (Disability-Adjusted Life Years),Russian Federation,Male,All Ages,Cardiovascular diseases,Rate,2013,16913.285219,17121.473215,16646.640694,Deaths,689.563171,698.231847,671.841370,True
96,DALYs (Disability-Adjusted Life Years),Russian Federation,Female,All Ages,Cardiovascular diseases,Rate,2013,12062.770301,12439.589972,11455.512603,Deaths,730.915208,756.090049,678.546166,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95820,DALYs (Disability-Adjusted Life Years),Uzbekistan,Female,All Ages,Unintentional injuries,Rate,2019,924.906883,1110.802656,764.324202,Deaths,8.090781,9.449337,6.931106,True
95821,DALYs (Disability-Adjusted Life Years),Uzbekistan,Both,All Ages,Unintentional injuries,Rate,2019,1489.541043,1751.864358,1263.197669,Deaths,16.076524,18.680623,13.813033,True
95873,DALYs (Disability-Adjusted Life Years),Armenia,Male,All Ages,Digestive diseases,Rate,2019,1890.952170,2175.781400,1600.627590,Deaths,65.149955,76.413600,54.884648,True
95874,DALYs (Disability-Adjusted Life Years),Armenia,Female,All Ages,Digestive diseases,Rate,2019,1134.309391,1299.771431,975.433185,Deaths,49.340143,57.384637,41.791501,True
95875,DALYs (Disability-Adjusted Life Years),Armenia,Both,All Ages,Digestive diseases,Rate,2019,1499.511198,1724.193941,1286.684471,Deaths,56.970919,66.339240,48.503861,True

In [287]:
# точно так же можно прописать любое сложное условие отдельной функцией, а затем применить к нужному столбцу
def if_cis(x):
    if x in CIS_2020:
        return True
    else:
        False

In [288]:
df_all['CIS_2020'] = df_all['location'].apply(if_cis)

In [289]:
df_all[df_all['CIS_2020'] == True]

,measure_x,location,sex,age,cause,metric,year,daly_val,daly_upper,daly_lower,measure_y,deaths_val,deaths_upper,deaths_lower,CIS_2020
26,DALYs (Disability-Adjusted Life Years),Russian Federation,Male,All Ages,Transport injuries,Rate,2013,2311.203652,2557.790575,2102.970106,Deaths,33.102775,33.670112,31.914774,True
27,DALYs (Disability-Adjusted Life Years),Russian Federation,Female,All Ages,Transport injuries,Rate,2013,1003.703949,1204.231323,826.997768,Deaths,10.021556,10.217613,9.439502,True
28,DALYs (Disability-Adjusted Life Years),Russian Federation,Both,All Ages,Transport injuries,Rate,2013,1610.409759,1827.886031,1418.823756,Deaths,20.731699,21.055609,19.955321,True
95,DALYs (Disability-Adjusted Life Years),Russian Federation,Male,All Ages,Cardiovascular diseases,Rate,2013,16913.285219,17121.473215,16646.640694,Deaths,689.563171,698.231847,671.841370,True
96,DALYs (Disability-Adjusted Life Years),Russian Federation,Female,All Ages,Cardiovascular diseases,Rate,2013,12062.770301,12439.589972,11455.512603,Deaths,730.915208,756.090049,678.546166,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95820,DALYs (Disability-Adjusted Life Years),Uzbekistan,Female,All Ages,Unintentional injuries,Rate,2019,924.906883,1110.802656,764.324202,Deaths,8.090781,9.449337,6.931106,True
95821,DALYs (Disability-Adjusted Life Years),Uzbekistan,Both,All Ages,Unintentional injuries,Rate,2019,1489.541043,1751.864358,1263.197669,Deaths,16.076524,18.680623,13.813033,True
95873,DALYs (Disability-Adjusted Life Years),Armenia,Male,All Ages,Digestive diseases,Rate,2019,1890.952170,2175.781400,1600.627590,Deaths,65.149955,76.413600,54.884648,True
95874,DALYs (Disability-Adjusted Life Years),Armenia,Female,All Ages,Digestive diseases,Rate,2019,1134.309391,1299.771431,975.433185,Deaths,49.340143,57.384637,41.791501,True
95875,DALYs (Disability-Adjusted Life Years),Armenia,Both,All Ages,Digestive diseases,Rate,2019,1499.511198,1724.193941,1286.684471,Deaths,56.970919,66.339240,48.503861,True

In [290]:
# сохраняем датафрейм в csv
df_all.to_csv('df_all.csv')

### 3. Работа с большими файлами с помощью аргумента chunksize

In [233]:
# разобьем большой файл на части с помощью аргумента chunksize, в котором прописывается сколько строк должно быть в каждой части
# выведем по 5 строк каждой получившейся части

for chunk_df in pd.read_csv('df_all.csv', 
                      chunksize = 50000):
    print("CHUNK DF")
    print(chunk_df.head())

CHUNK DF
   Unnamed: 0                               measure_x location     sex  \
0           0  DALYs (Disability-Adjusted Life Years)   Gambia  Female
1           1  DALYs (Disability-Adjusted Life Years)   Gambia    Both
2           2  DALYs (Disability-Adjusted Life Years)   Gambia    Male
3           3  DALYs (Disability-Adjusted Life Years)   Gambia  Female
4           4  DALYs (Disability-Adjusted Life Years)   Gambia    Both

        age                            cause metric  year     daly_val  \
0  All Ages  Maternal and neonatal disorders   Rate  2012  7475.212700
1  All Ages  Maternal and neonatal disorders   Rate  2012  7814.344518
2  All Ages          Substance use disorders   Rate  2012   179.493660
3  All Ages          Substance use disorders   Rate  2012    91.400543
4  All Ages          Substance use disorders   Rate  2012   134.688036

    daly_upper   daly_lower measure_y  deaths_val  deaths_upper  deaths_lower  \
0  9104.773541  6157.428603    Deaths   89.867238    110.176286     74.001324
1  9667.960848  6289.146375    Deaths   89.365457    111.497307     71.539316
2   230.104586   134.067784    Deaths    1.101136      1.545407      0.786638
3   124.025911    64.625204    Deaths    0.227136      0.296917      0.173921
4   171.782808    99.320179    Deaths    0.656605      0.896138      0.490594

  CIS_2020
0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
CHUNK DF
       Unnamed: 0                               measure_x location     sex  \
50000       50000  DALYs (Disability-Adjusted Life Years)    India    Both
50001       50001  DALYs (Disability-Adjusted Life Years)    India    Male
50002       50002  DALYs (Disability-Adjusted Life Years)    India  Female
50003       50003  DALYs (Disability-Adjusted Life Years)    India    Both
50004       50004  DALYs (Disability-Adjusted Life Years)   Turkey    Male

            age                            cause metric  year     daly_val  \
50000  All Ages        Other infectious diseases   Rate  2016   958.958618
50001  All Ages  Maternal and neonatal disorders   Rate  2016  3857.092523
50002  All Ages  Maternal and neonatal disorders   Rate  2016  3936.244203
50003  All Ages  Maternal and neonatal disorders   Rate  2016  3895.617080
50004  All Ages               Transport injuries   Rate  2016   906.078397

        daly_upper   daly_lower measure_y  deaths_val  deaths_upper  \
50000  1253.212194   758.548648    Deaths   14.064804     17.711690
50001  4559.365099  3248.746140    Deaths   39.804065     47.428130
50002  4575.786077  3357.759508    Deaths   42.591026     49.826017
50003  4578.291899  3318.975051    Deaths   41.160530     48.311924
50004  1044.082153   685.161081    Deaths   16.515202     19.376146

       deaths_lower CIS_2020
50000     11.444635      NaN
50001     33.085022      NaN
50002     36.112185      NaN
50003     34.780916      NaN
50004     11.913822      NaN

In [244]:
# применим метод groupby отдельно к каждой части и затем объединим результат в новый датафрейм
new_df = pd.DataFrame() # пустой датафрейм
for chunk_df in pd.read_csv('df_all.csv', 
                      chunksize = 50000):
    result = chunk_df.groupby(['cause', 'year']).agg({'deaths_val': 'mean',
                                                    'daly_val': 'mean'})
    new_df = pd.concat([new_df,result])

In [248]:
new_df

                              deaths_val     daly_val
cause                   year
Cardiovascular diseases 2011  112.889873  2945.949359
                        2012  238.128059  5118.690134
                        2013  236.486609  5005.051157
                        2014  242.057921  5088.816632
                        2015  253.292782  5250.955897
...                                  ...          ...
Unintentional injuries  2015   24.622137  1575.325187
                        2016   21.095357  1389.698018
                        2017   22.527506  1467.601676
                        2018   21.578766  1428.203221
                        2019   21.508796  1417.611000

[236 rows x 2 columns]

In [291]:
# сохраним результат в файл
new_df.to_csv('deaths_daly_groupby.csv', encoding = 'utf-8')

#### Вот и всё, вы молодцы!